# Generated by Django 3.1.7 on 2021-03-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='scale',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
