# Generated by Django 3.1.7 on 2021-03-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210310_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
