# Generated by Django 3.1.7 on 2021-04-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_orderitem_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
